name: mizania_proj
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.15.4
  google_fonts: ^8.1.0
  shared_preferences: ^2.5.5
  go_router: ^17.3.0
  fl_chart: ^1.2.0
  pdf: ^3.13.0
  printing: ^5.15.0
  flutter_riverpod: ^3.3.2
  flutter_spinkit: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/name.png
    - assets/1st.png
    - assets/2nd.png
    - assets/3rd.png
    - assets/4th.png
    - assets/5th.png
    - assets/6th.png
    - assets/profil_icon.png
    - assets/home_icon.png
    - assets/historique_icon.png
    - assets/budget_icon.png